format = "$username$hostname$directory$cmd_duration$python$fill$git_branch$git_state$git_status$line_break$character"
palette = "catppuccin_mocha"
[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[❯](bold #ff5555)"
success_symbol = "[❯](bold #f8f8f2)"
vimcmd_symbol = "[❮](bold #f8f8f2)"

[cmd_duration]
format = "[$duration]($style) "
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[fill]
symbol = " "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #ff5555"

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[username]
format = "[$user]($style) on "
style_user = "bold #bd93f9"
